/*
 * Fonts for the portable text layout (no OS text APIs): TrueType files parsed
 * with stb_truetype. The faces are the embedded Roboto (native/fonts/roboto,
 * gzip arrays generated by cmake/embed-files.cmake), inflated on first use.
 *
 * Roboto also stands in for the system font (SF on iOS and macOS, which may
 * not be redistributed), with SF's vertical metrics and its advances scaled to
 * SF's average width (see native/README.md, "Portable text layout").
 */

#pragma once

#include <cstddef>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace facebook::react::portabletext {

namespace detail {
struct StbFont;
StbFont *stbOpenFont(const unsigned char *data);
void stbCloseFont(StbFont *font);
int stbUnitsPerEm(const StbFont *font);
void stbVerticalMetrics(const StbFont *font, int *ascent, int *descent, int *lineGap);
int stbGlyphIndex(const StbFont *font, char32_t codepoint);
int stbGlyphAdvance(const StbFont *font, int glyph);
int stbGlyphKerning(const StbFont *font, int glyph1, int glyph2);
/// Inflates a raw deflate stream (no zlib header) of a known inflated size.
std::vector<uint8_t> inflateRaw(const unsigned char *data, std::size_t size, std::size_t expectedSize);
} // namespace detail

/// One parsed font file. Thread-safe: the glyph and kerning caches are locked.
class Face {
 public:
  Face(std::string name, int weight, bool italic, std::vector<uint8_t> bytes);
  ~Face();
  Face(const Face &) = delete;
  Face &operator=(const Face &) = delete;

  bool valid() const { return font_ != nullptr; }
  const std::string &name() const { return name_; }
  int weight() const { return weight_; }
  bool italic() const { return italic_; }

  /// hhea ascender / descender (positive) / line gap, in em.
  float ascent() const { return ascent_; }
  float descent() const { return descent_; }
  float lineGap() const { return lineGap_; }

  /// Glyph id for a code point, 0 when the font has none.
  int glyph(char32_t codepoint) const;
  /// Advance width of a glyph, em.
  float advance(int glyph) const;
  /// Kerning between two glyphs (kern table or GPOS pair adjustment), em.
  float kerning(int left, int right) const;

 private:
  struct Cache;
  std::string name_;
  int weight_;
  bool italic_;
  std::vector<uint8_t> bytes_;
  detail::StbFont *font_ = nullptr;
  float unitsPerEm_ = 1000;
  float ascent_ = 0.8f;
  float descent_ = 0.2f;
  float lineGap_ = 0;
  std::unique_ptr<Cache> cache_;
};

/// A resolved font. `face` is null only when no font data is available (the
/// build has no embedded fonts or inflating failed); then every glyph uses the
/// fallback widths below and ascent 0.93 em, descent 0.24 em (Roboto's).
struct Font {
  const Face *face = nullptr;
  /// > 0: every glyph has this advance (em). Used for monospace families,
  /// which have no embedded face: monospace fonts (Menlo, SF Mono, Roboto
  /// Mono, Droid Sans Mono, Courier) all advance 0.6 em.
  float fixedAdvanceEm = 0;
  /// > 0: the ascent / descent (em) instead of the face's. The system font
  /// stand-in has the system font's (SF: 1980 / 2048 and 432 / 2048, the
  /// same for every weight and size, observed with CoreText on macOS 26), so
  /// line heights match iOS.
  float ascentEm = 0;
  float descentEm = 0;
  /// > 0: the system font stand-in for this weight (100..900); its glyph
  /// advances are scaled by widthScale(size).
  int systemWeight = 0;
  bool systemItalic = false;

  /// The factor for the advances of glyphs in the face: 1, or for the system
  /// font stand-in SF's width relative to Roboto at this size and weight,
  /// measured with CoreText on macOS 26.5 (a 210-character pangram / lorem
  /// ipsum text, Roboto Regular / Medium / Bold / Italic as mapped here): SF
  /// tracks small sizes wider and switches to its display design at 20 pt.
  float widthScale(float size) const;

  /// em
  float ascent() const;
  float descent() const;
  bool operator==(const Font &other) const
  {
    return face == other.face && fixedAdvanceEm == other.fixedAdvanceEm && ascentEm == other.ascentEm &&
        descentEm == other.descentEm && systemWeight == other.systemWeight && systemItalic == other.systemItalic;
  }
};

/// The font for a family name (as given to <Text style={{fontFamily}}>),
/// weight 100..900 and italic:
///  - "" / "System" / "system-ui" / any family without an embedded face: the
///    system font stand-in: Roboto advances (weight <= 450 Regular, <= 550
///    Medium, else Bold; italic: Roboto Italic) scaled to SF's widths
///    (widthScale) with SF's ascent and descent.
///  - "Roboto", "sans-serif", "Roboto-<Style>", "sans-serif-medium" ...: Roboto
///    with the closest weight like the macOS layout (NSFontWeight distance:
///    100-400 Regular, 500-600 Medium, 700-900 Bold), "sans-serif-medium" /
///    "Roboto-Medium" Medium, "...-Bold" Bold, "...-Italic" Italic.
///  - "monospace", "ui-monospace", "Menlo", "Courier", "...Mono...": fixed
///    0.6 em advances with the Roboto vertical metrics.
Font resolveFont(const std::string &family, int weight, bool italic);

/// The embedded faces, inflated and parsed once (thread-safe). Returns the
/// number of usable faces (0 when the build has no embedded fonts).
int loadEmbeddedFaces();

/// Advance of a code point in `font` (em), with `glyphOut` its glyph id (0 when
/// the face has none and a fallback width is used: 1.0 em for CJK and
/// fullwidth forms, 0.9 em Hangul, 1.35 em emoji (the macOS CoreText widths of
/// PingFang / Apple Color Emoji), 0 for combining marks, joiners and variation
/// selectors, 0.55 em otherwise).
float codepointAdvance(const Font &font, char32_t codepoint, int &glyphOut);

} // namespace facebook::react::portabletext
