/*
 * See PortableFonts.h.
 */

#include "PortableFonts.h"

#include "EmbeddedFonts.h"

#include <algorithm>
#include <array>
#include <cctype>
#include <mutex>
#include <unordered_map>
#include <utility>

#if FANTOM_WITH_EMBEDDED_FONTS
// Generated by cmake/embed-files.cmake (gzip streams of native/fonts/roboto).
extern const unsigned char fantom_roboto_regular[];
extern const std::size_t fantom_roboto_regular_size;
extern const unsigned char fantom_roboto_medium[];
extern const std::size_t fantom_roboto_medium_size;
extern const unsigned char fantom_roboto_bold[];
extern const std::size_t fantom_roboto_bold_size;
extern const unsigned char fantom_roboto_italic[];
extern const std::size_t fantom_roboto_italic_size;
#endif

namespace facebook::react::portabletext {

struct Face::Cache {
  std::mutex mutex;
  std::unordered_map<char32_t, int> glyphs;
  std::unordered_map<int, float> advances;
  std::unordered_map<uint64_t, float> kerning;
};

Face::Face(std::string name, int weight, bool italic, std::vector<uint8_t> bytes)
    : name_(std::move(name)), weight_(weight), italic_(italic), bytes_(std::move(bytes)), cache_(new Cache()) {
  if (bytes_.empty()) {
    return;
  }
  font_ = detail::stbOpenFont(bytes_.data());
  if (font_ == nullptr) {
    return;
  }
  unitsPerEm_ = static_cast<float>(std::max(detail::stbUnitsPerEm(font_), 16));
  int ascent = 0;
  int descent = 0;
  int lineGap = 0;
  detail::stbVerticalMetrics(font_, &ascent, &descent, &lineGap);
  ascent_ = static_cast<float>(ascent) / unitsPerEm_;
  descent_ = static_cast<float>(-descent) / unitsPerEm_;
  lineGap_ = static_cast<float>(lineGap) / unitsPerEm_;
}

Face::~Face() {
  if (font_ != nullptr) {
    detail::stbCloseFont(font_);
  }
}

int Face::glyph(char32_t codepoint) const {
  if (font_ == nullptr) {
    return 0;
  }
  std::lock_guard<std::mutex> lock(cache_->mutex);
  auto it = cache_->glyphs.find(codepoint);
  if (it != cache_->glyphs.end()) {
    return it->second;
  }
  int id = detail::stbGlyphIndex(font_, codepoint);
  cache_->glyphs.emplace(codepoint, id);
  return id;
}

float Face::advance(int glyph) const {
  if (font_ == nullptr) {
    return 0;
  }
  std::lock_guard<std::mutex> lock(cache_->mutex);
  auto it = cache_->advances.find(glyph);
  if (it != cache_->advances.end()) {
    return it->second;
  }
  float advance = static_cast<float>(detail::stbGlyphAdvance(font_, glyph)) / unitsPerEm_;
  cache_->advances.emplace(glyph, advance);
  return advance;
}

float Face::kerning(int left, int right) const {
  if (font_ == nullptr || left == 0 || right == 0) {
    return 0;
  }
  uint64_t key = (static_cast<uint64_t>(static_cast<uint32_t>(left)) << 32) | static_cast<uint32_t>(right);
  std::lock_guard<std::mutex> lock(cache_->mutex);
  auto it = cache_->kerning.find(key);
  if (it != cache_->kerning.end()) {
    return it->second;
  }
  float kerning = static_cast<float>(detail::stbGlyphKerning(font_, left, right)) / unitsPerEm_;
  cache_->kerning.emplace(key, kerning);
  return kerning;
}

namespace {

constexpr float kFallbackAscent = 0.927734f; // Roboto hhea 1900 / 2048
constexpr float kFallbackDescent = 0.244141f; // Roboto hhea 500 / 2048
constexpr float kSystemAscent = 1980.0f / 2048; // SF (NSFont.systemFont ascender / size)
constexpr float kSystemDescent = 432.0f / 2048;

struct FaceSet {
  std::vector<std::unique_ptr<Face>> faces;
  const Face *regular = nullptr;
  const Face *medium = nullptr;
  const Face *bold = nullptr;
  const Face *italic = nullptr;
};

#if FANTOM_WITH_EMBEDDED_FONTS
/// Inflates a gzip stream (RFC 1952).
std::vector<uint8_t> gunzip(const unsigned char *data, std::size_t size) {
  if (size < 18 || data[0] != 0x1f || data[1] != 0x8b || data[2] != 8) {
    return {};
  }
  uint8_t flags = data[3];
  std::size_t offset = 10;
  if ((flags & 0x04) != 0) { // FEXTRA
    if (offset + 2 > size) {
      return {};
    }
    offset += 2 + static_cast<std::size_t>(data[offset] | (data[offset + 1] << 8));
  }
  for (uint8_t bit : {uint8_t{0x08}, uint8_t{0x10}}) { // FNAME, FCOMMENT
    if ((flags & bit) != 0) {
      while (offset < size && data[offset] != 0) {
        offset++;
      }
      offset++;
    }
  }
  if ((flags & 0x02) != 0) { // FHCRC
    offset += 2;
  }
  if (offset + 8 > size) {
    return {};
  }
  const unsigned char *trailer = data + size - 4;
  std::size_t inflatedSize = static_cast<std::size_t>(trailer[0]) | (static_cast<std::size_t>(trailer[1]) << 8) |
      (static_cast<std::size_t>(trailer[2]) << 16) | (static_cast<std::size_t>(trailer[3]) << 24);
  return detail::inflateRaw(data + offset, size - offset - 8, inflatedSize);
}
#endif

const FaceSet &faceSet() {
  static FaceSet set;
  static std::once_flag once;
  std::call_once(once, [] {
#if FANTOM_WITH_EMBEDDED_FONTS
    struct Blob {
      const char *name;
      int weight;
      bool italic;
      const unsigned char *data;
      std::size_t size;
      const Face **slot;
    };
    const Blob blobs[] = {
        {"Roboto-Regular", 400, false, fantom_roboto_regular, fantom_roboto_regular_size, &set.regular},
        {"Roboto-Medium", 500, false, fantom_roboto_medium, fantom_roboto_medium_size, &set.medium},
        {"Roboto-Bold", 700, false, fantom_roboto_bold, fantom_roboto_bold_size, &set.bold},
        {"Roboto-Italic", 400, true, fantom_roboto_italic, fantom_roboto_italic_size, &set.italic},
    };
    for (const auto &blob : blobs) {
      auto face = std::make_unique<Face>(blob.name, blob.weight, blob.italic, gunzip(blob.data, blob.size));
      if (face->valid()) {
        *blob.slot = face.get();
        set.faces.push_back(std::move(face));
      }
    }
#endif
    // Missing faces fall back to the nearest one that loaded.
    const Face *any = set.regular != nullptr ? set.regular
        : set.medium != nullptr              ? set.medium
        : set.bold != nullptr                ? set.bold
                                             : set.italic;
    if (set.regular == nullptr) {
      set.regular = any;
    }
    if (set.medium == nullptr) {
      set.medium = set.regular;
    }
    if (set.bold == nullptr) {
      set.bold = set.medium;
    }
    if (set.italic == nullptr) {
      set.italic = set.regular;
    }
  });
  return set;
}

std::string lowercase(const std::string &s) {
  std::string out = s;
  std::transform(out.begin(), out.end(), out.begin(), [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
  return out;
}

bool startsWith(const std::string &s, const char *prefix) {
  return s.rfind(prefix, 0) == 0;
}

bool contains(const std::string &s, const char *part) {
  return s.find(part) != std::string::npos;
}

bool endsWith(const std::string &s, const std::string &suffix) {
  return s.size() >= suffix.size() && s.compare(s.size() - suffix.size(), suffix.size(), suffix) == 0;
}

bool inRange(char32_t c, char32_t first, char32_t last) {
  return c >= first && c <= last;
}

} // namespace

float Font::ascent() const {
  if (ascentEm > 0) {
    return ascentEm;
  }
  return face != nullptr ? face->ascent() : kFallbackAscent;
}

float Font::descent() const {
  if (descentEm > 0) {
    return descentEm;
  }
  return face != nullptr ? face->descent() : kFallbackDescent;
}

namespace {

// SF width / Roboto width (see Font::widthScale), by size and weight.
constexpr std::array<float, 21> kWidthSizes{8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 24, 28, 32, 36, 40, 48, 64};
constexpr std::array<std::array<float, 21>, 10> kWidthScales{{
    {1.075f, 1.060f, 1.046f, 1.033f, 1.021f, 1.008f, 0.998f, 0.987f, 0.979f, 0.966f, 0.962f,
     0.957f, 0.938f, 0.918f, 0.907f, 0.903f, 0.901f, 0.896f, 0.893f, 0.889f, 0.881f}, // 100
    {1.085f, 1.070f, 1.056f, 1.043f, 1.031f, 1.018f, 1.008f, 0.997f, 0.989f, 0.976f, 0.972f,
     0.968f, 0.949f, 0.930f, 0.920f, 0.917f, 0.915f, 0.910f, 0.908f, 0.904f, 0.896f}, // 200
    {1.106f, 1.091f, 1.076f, 1.064f, 1.051f, 1.039f, 1.028f, 1.018f, 1.010f, 0.997f, 0.993f,
     0.989f, 0.972f, 0.956f, 0.949f, 0.947f, 0.945f, 0.940f, 0.938f, 0.934f, 0.925f}, // 300
    {1.121f, 1.107f, 1.092f, 1.080f, 1.067f, 1.055f, 1.044f, 1.034f, 1.025f, 1.013f, 1.009f,
     1.006f, 0.989f, 0.976f, 0.970f, 0.970f, 0.968f, 0.963f, 0.961f, 0.957f, 0.948f}, // 400
    {1.135f, 1.121f, 1.106f, 1.094f, 1.081f, 1.069f, 1.058f, 1.048f, 1.040f, 1.027f, 1.024f,
     1.021f, 1.005f, 0.992f, 0.988f, 0.989f, 0.987f, 0.982f, 0.980f, 0.975f, 0.967f}, // 500
    {1.145f, 1.131f, 1.116f, 1.104f, 1.092f, 1.079f, 1.069f, 1.059f, 1.050f, 1.038f, 1.035f,
     1.031f, 1.016f, 1.005f, 1.001f, 1.002f, 1.000f, 0.995f, 0.993f, 0.989f, 0.981f}, // 600
    {1.168f, 1.153f, 1.139f, 1.127f, 1.114f, 1.102f, 1.092f, 1.081f, 1.073f, 1.061f, 1.058f,
     1.055f, 1.040f, 1.029f, 1.027f, 1.029f, 1.027f, 1.022f, 1.020f, 1.015f, 1.007f}, // 700
    {1.201f, 1.187f, 1.172f, 1.160f, 1.147f, 1.135f, 1.125f, 1.114f, 1.106f, 1.094f, 1.091f,
     1.088f, 1.074f, 1.065f, 1.064f, 1.067f, 1.065f, 1.060f, 1.058f, 1.054f, 1.046f}, // 800
    {1.230f, 1.215f, 1.201f, 1.189f, 1.176f, 1.164f, 1.154f, 1.143f, 1.135f, 1.123f, 1.120f,
     1.117f, 1.104f, 1.097f, 1.097f, 1.101f, 1.099f, 1.094f, 1.092f, 1.087f, 1.079f}, // 900
    {1.156f, 1.141f, 1.126f, 1.113f, 1.100f, 1.087f, 1.076f, 1.065f, 1.057f, 1.044f, 1.041f,
     1.038f, 1.025f, 1.018f, 1.019f, 1.023f, 1.021f, 1.015f, 1.013f, 1.009f, 1.000f}, // 400 italic
}};

float interpolateScale(const std::array<float, 21> &row, float size) {
  if (size <= kWidthSizes.front()) {
    return row.front();
  }
  for (std::size_t i = 1; i < kWidthSizes.size(); i++) {
    if (size <= kWidthSizes[i]) {
      float t = (size - kWidthSizes[i - 1]) / (kWidthSizes[i] - kWidthSizes[i - 1]);
      return row[i - 1] + t * (row[i] - row[i - 1]);
    }
  }
  return row.back();
}

} // namespace

float Font::widthScale(float size) const {
  if (systemWeight <= 0) {
    return 1;
  }
  std::size_t index = static_cast<std::size_t>(std::clamp((systemWeight + 50) / 100, 1, 9) - 1);
  float scale = interpolateScale(kWidthScales[index], size);
  if (systemItalic) {
    // Only the regular italic was measured: the same weight ratio as upright.
    scale *= interpolateScale(kWidthScales[9], size) / interpolateScale(kWidthScales[3], size);
  }
  return scale;
}

int loadEmbeddedFaces() {
  return static_cast<int>(faceSet().faces.size());
}

Font resolveFont(const std::string &family, int weight, bool italic) {
  const FaceSet &set = faceSet();
  std::string name = lowercase(family);
  Font font;

  if (name == "monospace" || name == "ui-monospace" || contains(name, "mono") || contains(name, "menlo") ||
      contains(name, "courier") || contains(name, "consolas")) {
    font.face = set.regular;
    font.fixedAdvanceEm = 0.6f;
    return font;
  }

  bool roboto = startsWith(name, "roboto") || startsWith(name, "sans-serif");
  if (roboto) {
    // A face name ("Roboto-Bold", "sans-serif-medium") picks that face.
    if (endsWith(name, "-italic") || contains(name, "italic")) {
      font.face = set.italic;
      return font;
    }
    if (endsWith(name, "-bold") || endsWith(name, "-black")) {
      font.face = set.bold;
      return font;
    }
    if (endsWith(name, "-medium")) {
      font.face = set.medium;
      return font;
    }
    if (endsWith(name, "-regular") || endsWith(name, "-light") || endsWith(name, "-thin")) {
      font.face = set.regular;
      return font;
    }
    if (italic) {
      font.face = set.italic;
    } else if (weight >= 700) {
      font.face = set.bold;
    } else if (weight >= 500) {
      font.face = set.medium;
    } else {
      font.face = set.regular;
    }
    return font;
  }

  // The system font (and families without an embedded face, which macOS
  // also measures with the system font).
  font.ascentEm = kSystemAscent;
  font.descentEm = kSystemDescent;
  font.systemWeight = std::clamp(weight, 100, 900);
  font.systemItalic = italic;
  if (italic) {
    font.face = set.italic;
  } else if (weight > 550) {
    font.face = set.bold;
  } else if (weight > 450) {
    font.face = set.medium;
  } else {
    font.face = set.regular;
  }
  return font;
}

float codepointAdvance(const Font &font, char32_t c, int &glyphOut) {
  glyphOut = 0;
  // Zero-width: joiners, variation selectors, emoji modifiers and tags,
  // combining marks without a glyph.
  if (c == 0x200B || c == 0x200C || c == 0x200D || c == 0x2060 || c == 0xFEFF || inRange(c, 0xFE00, 0xFE0F) ||
      inRange(c, 0x1F3FB, 0x1F3FF) || inRange(c, 0xE0020, 0xE007F) || inRange(c, 0xE0100, 0xE01EF)) {
    return 0;
  }
  if (font.fixedAdvanceEm > 0) {
    bool wide = inRange(c, 0x1100, 0x115F) || inRange(c, 0x2E80, 0xA4CF) || inRange(c, 0xAC00, 0xD7A3) ||
        inRange(c, 0xF900, 0xFAFF) || inRange(c, 0xFF00, 0xFF60) || inRange(c, 0x20000, 0x3FFFD);
    bool mark = inRange(c, 0x0300, 0x036F);
    return mark ? 0 : (wide ? 2 * font.fixedAdvanceEm : font.fixedAdvanceEm);
  }
  if (font.face != nullptr) {
    int glyph = font.face->glyph(c);
    if (glyph != 0) {
      glyphOut = glyph;
      return font.face->advance(glyph);
    }
  }
  if (inRange(c, 0x0300, 0x036F) || inRange(c, 0x1AB0, 0x1AFF) || inRange(c, 0x1DC0, 0x1DFF) ||
      inRange(c, 0x20D0, 0x20FF) || inRange(c, 0xFE20, 0xFE2F)) {
    return 0;
  }
  if (inRange(c, 0x1100, 0x11FF) || inRange(c, 0xAC00, 0xD7A3) || inRange(c, 0x3130, 0x318F)) {
    return 0.9f;
  }
  if (inRange(c, 0x2E80, 0x303E) || inRange(c, 0x3040, 0x312F) || inRange(c, 0x3190, 0x4DBF) ||
      inRange(c, 0x4E00, 0x9FFF) || inRange(c, 0xA000, 0xA4CF) || inRange(c, 0xF900, 0xFAFF) ||
      inRange(c, 0xFE30, 0xFE4F) || inRange(c, 0xFF00, 0xFF60) || inRange(c, 0xFFE0, 0xFFE6) ||
      inRange(c, 0x20000, 0x3FFFD)) {
    return 1.0f;
  }
  if (inRange(c, 0x1F000, 0x1FAFF) || inRange(c, 0x2600, 0x27BF) || inRange(c, 0x2B00, 0x2BFF)) {
    return 1.35f;
  }
  return 0.55f;
}

} // namespace facebook::react::portabletext

namespace facebook::react {

int registerEmbeddedFonts() {
  return portabletext::loadEmbeddedFaces();
}

} // namespace facebook::react
