# Generates a C++ source with the gzip-compressed bytes of some files.
#
#   cmake -DOUTPUT=<out.cpp> -DWORK_DIR=<dir> -DNAMES="a;b" -DFILES="<abs path>;<abs path>" -P embed-files.cmake
#
# For each file: `extern const unsigned char <name>[]` (a gzip stream) and
# `extern const std::size_t <name>_size`. EmbeddedFonts.mm inflates them.
cmake_minimum_required(VERSION 3.18)

set(out "// Generated by embed-files.cmake from:\n")
foreach(file ${FILES})
  string(APPEND out "//   ${file}\n")
endforeach()
string(APPEND out "// Do not edit.\n\n#include <cstddef>\n\n")

file(MAKE_DIRECTORY "${WORK_DIR}")
list(LENGTH NAMES count)
math(EXPR last "${count} - 1")
foreach(i RANGE ${last})
  list(GET NAMES ${i} name)
  list(GET FILES ${i} file)
  # file(ARCHIVE_CREATE) resolves PATHS relative to the working directory, so
  # compress from the file's own directory.
  get_filename_component(dir "${file}" DIRECTORY)
  get_filename_component(base "${file}" NAME)
  set(gz "${WORK_DIR}/${name}.gz")
  execute_process(
    COMMAND "${CMAKE_COMMAND}" -DIN=${base} -DOUT=${gz} -P "${CMAKE_CURRENT_LIST_DIR}/gzip-file.cmake"
    WORKING_DIRECTORY "${dir}"
    RESULT_VARIABLE result)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "embed-files: cannot compress ${file}")
  endif()
  file(READ "${gz}" hex HEX)
  # Zero the gzip MTIME field (bytes 4-7) so the output is reproducible.
  string(SUBSTRING "${hex}" 0 8 head)
  string(SUBSTRING "${hex}" 16 -1 tail)
  set(hex "${head}00000000${tail}")
  string(LENGTH "${hex}" hexlen)
  math(EXPR size "${hexlen} / 2")
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
  string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){32})" "\\1\n" bytes "${bytes}")
  string(APPEND out "extern const unsigned char ${name}[] = {\n${bytes}\n};\n")
  string(APPEND out "extern const std::size_t ${name}_size = ${size};\n\n")
endforeach()

# Only rewrite when the content changes, so dependents do not rebuild.
if(EXISTS "${OUTPUT}")
  file(READ "${OUTPUT}" previous)
  if(previous STREQUAL out)
    return()
  endif()
endif()
file(WRITE "${OUTPUT}" "${out}")
